version: "3.7"

services:
  
  ubuntu:
    container_name: ubuntu
    build: ./ubuntu
    image: ubuntu:20.04
    ports:
     - 3307:80
    
  
  mysql:
    container_name: mySQL
    build: ./database
    image: mysql/mysql-server:8.0
    ports:
      - 3306:3306
    